[package]
    name = "bevy_blend_depth_order_issue_reproducible"
    version = "0.1.0"
    edition = "2021"

[dependencies]
    bevy = { git = "https://github.com/floppyhammer/bevy", branch="fix-camera-distance" }